version: '3'
services:
  git-package:
    build:
      context: "."
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:80
    volumes:
      - type: bind
        source: ./dist
        target: /usr/share/nginx/html
    working_dir: /dist